[package]
name = "snowman"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.8", features = ["std", "getrandom"] }
rand_core = { version = "0.6", features = ["getrandom"] }
zeroize = { version = "1.8", features = ["derive"] }
hex = "0.4"
bip39 = "2.0"
sha2 = "0.10.9"
